services:
  log_analyzer:
    environment:
      - PATH=/root/.pyenv/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    build:
      dockerfile: Dockerfile
    ports:
      - '8888:8888'
    volumes:
      - ./logs:/opt/app/logs
      - ./reports:/opt/app/reports
      - ./templates:/opt/app/templates
